### ISSUE TITLE
Agregar tecnologías

### ISSUE THREAD

**Issue by pGriot** [MariaFlor87/portfolio-template#1]
Hola Florencia, me parece que te falta agregar el apartado tecnologías.

Saludos

**Comment by florencia-uruzagasti** [comment]
Hola! Siguiendo con la actividad, ¿pudiste hacer el **_fork_**? no me ha llegado nada aun. 
Saludos

**Comment by pGriot** [comment]
Si, pude hacer el fork pero todavía no mandé la solicitud de pull porque con mi resolución los íconos se ven muy grandes y te afean la página, estoy tratando de corregir eso y que se vea bien en cualquier pantalla antes de mandartelo.

Ahora se ve así:
![image](https://user-images.githubusercontent.com/104875289/177415381-338c2242-482d-42d7-9629-f172a281baec.png)

**Comment by florencia-uruzagasti** [comment]
Disculpa, tengo exactamente el mismo error con los iconos ¿Cómo lo solucionaste? ya revise y no encuentro el error...

**Comment by pGriot** [comment]
Tuve que agregar las líneas que marqué con verde en el .css

![image](https://user-images.githubusercontent.com/104875289/177448509-28e84bbf-3279-439c-8d6e-e88fc5b88d18.png)

En principio con ``flex-grow: 0.8;`` debería funcionar pero ya había agregado las otras y funcionó. Quizás tengas que jugar con el 0.8 (1 es 100%, 0.8 el 80% y así)

En este [enlace](https://developer.mozilla.org/es/docs/Web/CSS/flex-grow) tenés más info de la propiedad y [acá](https://developer.mozilla.org/es/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox) está sobre flexbox completa

**Comment by florencia-uruzagasti** [comment]
Gracias! justo estaba modificando esas líneas y por fin se arreglo, ahora tengo este problema: 
![image](https://user-images.githubusercontent.com/107757084/177450942-6ae1db8f-dd42-4c73-a606-5708c792aa9a.png)

En cuanto pueda corregirlo, termino de hacer lo que falta 🙂
